### PR TITLE
docs(deps): remove all testmate references

### PR DESCRIPTION
**Pull request by oxcafedead**
Reason: TestMate has been decommissioned and is no longer supported.

## Summary

This PR removes all TestMate references from the codemie docs.

## Changes

Removed testmate from all places where it's mentioned, including spell config.

## Testing

- [x] Tested locally with `npm start`
- [x] All pages render correctly
- [x] Images display properly
- [x] Internal links work
- [x] Sidebar navigation works

## Quality Checks

- [x] `npm run check` passes (typecheck + lint + commitlint)
- [x] No MDX compilation errors
- [x] No raw angle brackets (`<text>` must be `` `<text>` ``)
- [x] Sidebar references document IDs (not filenames)
- [x] Images stored locally next to content (not in `static/img/`)
- [x] Commit messages follow Conventional Commits
- [x] No secrets or credentials in documentation

---

BTW, conventional commits forced me create incorrect and bad commit message (scopes are incorrect).
```
⧗   input: docs(testmate): remove all TestMate references

Reason: TestMate has been decommissioned and is no longer supported.
✖   subject must be lower-case [subject-case]
✖   scope must be one of [aws, gcp, user-guide, deployment, getting-started, config, deps] [scope-enum]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

Absolutely valid commit message was rejected. TestMate should be in capitals because it's a given name.
This commit / PR touches multiple "scopes" which is not covered by conventional commits.
Feel free to rename it if you see the correct message title.

### CODE REVIEW

**Review by elluvium — APPROVED** [review]

**Review by Artem-Zahumonnyi — APPROVED** [review]

**Comment by elluvium** [comment]
@oxcafedead Thank you for opening MR! We really appreciate it
